#!/usr/bin/env python3
"""
Advanced Text Cipher Engine
---------------------------
Implements a stream cipher based on key derivation (SHA-256) and XOR/Modular
stream expansion. Uses dynamic salting to ensure identical plaintexts produce
completely different ciphertexts when encrypted multiple times.
"""

import os
import hashlib


def derive_keystream(passphrase: str, salt: bytes, length: int) -> bytes:
    """
    Derives a pseudo-random keystream of arbitrary length using a passphrase
    and dynamic salt via iterative SHA-256 hashing.

    :param passphrase: User-provided secret passphrase.
    :param salt: Random cryptographic salt (8 bytes).
    :param length: Required length of the keystream in bytes.
    :return: A byte array matching the requested length.
    """
    keystream = bytearray()
    counter = 0

    while len(keystream) < length:
        # Create a unique block input combining salt, passphrase, and block counter
        hash_input = salt + passphrase.encode('utf-8') + counter.to_bytes(4, byteorder='big')
        block = hashlib.sha256(hash_input).digest()
        keystream.extend(block)
        counter += 1

    return bytes(keystream[:length])


def encrypt(plaintext: str, passphrase: str) -> str:
    """
    Encrypts a string using a keystream derived from SHA-256 and a random salt.

    Logic:
    1. Generate an 8-byte random salt to prevent identical ciphertexts.
    2. Convert plaintext to UTF-8 bytes.
    3. Generate a keystream matching the plaintext length.
    4. XOR each plaintext byte with its corresponding keystream byte.
    5. Return hexadecimal representation containing [Salt] + [Ciphertext].

    :param plaintext: Text to encrypt.
    :param passphrase: Secret key used to generate the keystream.
    :return: Hexadecimal string representing encrypted data.
    """
    salt = os.urandom(8)  # 64-bit random salt
    plaintext_bytes = plaintext.encode('utf-8')
    
    keystream = derive_keystream(passphrase, salt, len(plaintext_bytes))
    
    # Perform bitwise XOR between message bytes and key stream
    ciphertext_bytes = bytes([p ^ k for p, k in zip(plaintext_bytes, keystream)])
    
    # Combine salt + ciphertext into a single output
    combined = salt + ciphertext_bytes
    return combined.hex()


def decrypt(hex_ciphertext: str, passphrase: str) -> str:
    """
    Decrypts a hexadecimal cipher string generated by encrypt().

    :param hex_ciphertext: Hexadecimal string containing salt and ciphertext.
    :param passphrase: Secret key used during encryption.
    :return: Decrypted plaintext string.
    :raises ValueError: If input format is invalid or decryption fails.
    """
    try:
        data = bytes.fromhex(hex_ciphertext.strip())
        if len(data) < 8:
            raise ValueError("Ciphertext is too short to be valid.")
        
        # Extract salt (first 8 bytes) and ciphertext
        salt = data[:8]
        ciphertext_bytes = data[8:]
        
        keystream = derive_keystream(passphrase, salt, len(ciphertext_bytes))
        
        # XORing ciphertext again with identical keystream restores the original bytes
        decrypted_bytes = bytes([c ^ k for c, k in zip(ciphertext_bytes, keystream)])
        
        return decrypted_bytes.decode('utf-8')
    except (ValueError, UnicodeDecodeError):
        raise ValueError("Decryption failed. Incorrect key or corrupted ciphertext.")


def main() -> None:
    """Main CLI Menu loop."""
    print("========================================")
    print("   ADVANCED STREAM CIPHER ENGINE        ")
    print("========================================")

    while True:
        print("\nMain Menu:")
        print("1. Encrypt a message")
        print("2. Decrypt a message")
        print("3. Exit")

        choice = input("\nSelect an option (1-3): ").strip()

        if choice == '1':
            message = input("\nEnter the plaintext to encrypt: ")
            passphrase = input("Enter a secret passphrase: ")
            if not passphrase:
                print("Error: Passphrase cannot be empty.")
                continue

            encrypted_hex = encrypt(message, passphrase)
            print("\n" + "=" * 50)
            print(" Encrypted Ciphertext (Hex format):")
            print(f" {encrypted_hex}")
            print("=" * 50)

        elif choice == '2':
            hex_ciphertext = input("\nEnter the hex ciphertext: ")
            passphrase = input("Enter the secret passphrase: ")
            if not passphrase:
                print("Error: Passphrase cannot be empty.")
                continue

            try:
                decrypted_text = decrypt(hex_ciphertext, passphrase)
                print("\n" + "=" * 50)
                print(f" Decrypted Plaintext: {decrypted_text}")
                print("=" * 50)
            except ValueError as err:
                print(f"\n[!] {err}")

        elif choice == '3':
            print("\nExiting engine. Goodbye!")
            break
        else:
            print("\nError: Invalid selection. Please choose 1, 2, or 3.")


if __name__ == "__main__":
    main()
